# active spring boot profile
spring:
   profiles:
      active: dev

---
# common spring boot configuration
spring:

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # htttp
   http:
      encoding:
         charset: UTF-8
         enabled: true
         forced: true
         forced-request: true
         forced-response: true

   # message resource(Internationaliztion)
   messages:
      always-message-format: true
      basename: messages/messages_ko
      encoding: UTF-8

   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB

   aop:
      auto: true
      proxy-target-class: true

---
# dev profile - spring boot configuration 
spring:
   profiles: dev

   # devtools enabled
   devtools:
      livereload:
         enabled: true

   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf8
      username: postgres
      password: 1234
      initialSize: 10
      maxActive: 100

---
# production profile - spring boot configuration
spring:
   profiles: production

   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=utf8
      username: postgres
      password: 1234
      initialSize: 10
      maxActive: 100
---
# server
server:
   port: 8080
   servlet:
      context-path: /ucare_backend

---
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

---
#logging
logging:
   config: classpath:logback.xml